import { PrismaClient, OutletType } from "@prisma/client";

const prisma = new PrismaClient();

interface DealerData {
  name: string;
  brandSlug: string;
  vehicleSlug: string;
  dealerCode: string;
  outletType: OutletType;
  address: string;
  city: string;
  state: string;
  pincode: string;
  phone: string;
  email: string;
  rating: number;
  reviewCount: number;
  latitude: number;
  longitude: number;
  googleMapsUrl: string;
  operatingHours: string;
}

const DEALERS_SEED: DealerData[] = [
  // =========================================================================
  // 1. ŠKODA AUTO INDIA DEALERS (Serving Škoda Slavia)
  // =========================================================================
  {
    name: "Ring Road Škoda — Moti Nagar",
    brandSlug: "skoda",
    vehicleSlug: "skoda-slavia",
    dealerCode: "SK-DEL-01",
    outletType: OutletType.THREE_S_FACILITY,
    address: "C-114, Mayapuri Industrial Area Phase II, Near Moti Nagar Metro",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110064",
    phone: "+91 98101 23456",
    email: "sales.motinagar@ringroadskoda.co.in",
    rating: 4.7,
    reviewCount: 420,
    latitude: 28.6369,
    longitude: 77.1354,
    googleMapsUrl: "https://maps.google.com/?q=Ring+Road+Skoda+Moti+Nagar+Delhi",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Frontier Škoda — Gurugram",
    brandSlug: "skoda",
    vehicleSlug: "skoda-slavia",
    dealerCode: "SK-GGN-02",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Plot No. 14, Sector 18, Electronic City, Maruti Industrial Area",
    city: "Gurugram",
    state: "Haryana",
    pincode: "122008",
    phone: "+91 99100 87654",
    email: "gurugram.frontierskoda@frontierauto.in",
    rating: 4.6,
    reviewCount: 380,
    latitude: 28.4872,
    longitude: 77.0688,
    googleMapsUrl: "https://maps.google.com/?q=Frontier+Skoda+Sector+18+Gurugram",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Brite Škoda — Noida",
    brandSlug: "skoda",
    vehicleSlug: "skoda-slavia",
    dealerCode: "SK-NOI-03",
    outletType: OutletType.SHOWROOM,
    address: "B-8, Sector 63, Main Road, Electronic City",
    city: "Noida",
    state: "Uttar Pradesh",
    pincode: "201301",
    phone: "+91 98115 44321",
    email: "sales@briteskoda.com",
    rating: 4.5,
    reviewCount: 290,
    latitude: 28.6279,
    longitude: 77.3811,
    googleMapsUrl: "https://maps.google.com/?q=Brite+Skoda+Sector+63+Noida",
    operatingHours: "9:30 AM - 7:00 PM (Mon-Sun)",
  },
  {
    name: "Autobahn Škoda — Andheri West",
    brandSlug: "skoda",
    vehicleSlug: "skoda-slavia",
    dealerCode: "SK-MUM-04",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Unit 1, Shree Laxmi Industrial Estate, New Link Road, Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400053",
    phone: "+91 99201 55678",
    email: "andheri.sales@autobahnskoda.com",
    rating: 4.8,
    reviewCount: 510,
    latitude: 19.1418,
    longitude: 72.8312,
    googleMapsUrl: "https://maps.google.com/?q=Autobahn+Skoda+Andheri+West+Mumbai",
    operatingHours: "9:30 AM - 8:00 PM (Mon-Sun)",
  },
  {
    name: "JMD Škoda — Thane",
    brandSlug: "skoda",
    vehicleSlug: "skoda-slavia",
    dealerCode: "SK-THN-05",
    outletType: OutletType.SHOWROOM,
    address: "Eastern Express Highway, Near Nitin Casting, Panch Pakhadi",
    city: "Thane",
    state: "Maharashtra",
    pincode: "400602",
    phone: "+91 98202 33441",
    email: "thane.sales@jmdskoda.com",
    rating: 4.6,
    reviewCount: 310,
    latitude: 19.1982,
    longitude: 72.9644,
    googleMapsUrl: "https://maps.google.com/?q=JMD+Skoda+Thane+Mumbai",
    operatingHours: "10:00 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Tafe Access Škoda — St. Marks Road",
    brandSlug: "skoda",
    vehicleSlug: "skoda-slavia",
    dealerCode: "SK-BLR-06",
    outletType: OutletType.SHOWROOM,
    address: "No. 49, St. Marks Road, Ashok Nagar, Central Business District",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560001",
    phone: "+91 98450 11223",
    email: "stmarks@tafeaccessskoda.in",
    rating: 4.7,
    reviewCount: 460,
    latitude: 12.9719,
    longitude: 77.6015,
    googleMapsUrl: "https://maps.google.com/?q=Tafe+Access+Skoda+St+Marks+Road+Bengaluru",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Raja Škoda — Electronic City",
    brandSlug: "skoda",
    vehicleSlug: "skoda-slavia",
    dealerCode: "SK-BLR-07",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Hosur Main Road, Kudlu Gate, Near Electronic City Flyover",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560068",
    phone: "+91 98455 66778",
    email: "sales.ecity@rajaskoda.com",
    rating: 4.6,
    reviewCount: 340,
    latitude: 12.8891,
    longitude: 77.6432,
    googleMapsUrl: "https://maps.google.com/?q=Raja+Skoda+Kudlu+Gate+Bengaluru",
    operatingHours: "9:00 AM - 7:00 PM (Mon-Sun)",
  },
  {
    name: "Bhandari Škoda — Wakad",
    brandSlug: "skoda",
    vehicleSlug: "skoda-slavia",
    dealerCode: "SK-PUN-08",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Mumbai-Bengaluru Highway Bypass, Near Bhumkar Chowk, Wakad",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411057",
    phone: "+91 98220 88990",
    email: "wakad@bhandariskoda.com",
    rating: 4.7,
    reviewCount: 395,
    latitude: 18.5987,
    longitude: 73.7628,
    googleMapsUrl: "https://maps.google.com/?q=Bhandari+Skoda+Wakad+Pune",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Mahavir Škoda — Jubilee Hills",
    brandSlug: "skoda",
    vehicleSlug: "skoda-slavia",
    dealerCode: "SK-HYD-09",
    outletType: OutletType.SHOWROOM,
    address: "Road No. 36, CBI Colony, Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500033",
    phone: "+91 98490 22334",
    email: "jubileehills@mahavirskoda.com",
    rating: 4.8,
    reviewCount: 480,
    latitude: 17.4325,
    longitude: 78.4071,
    googleMapsUrl: "https://maps.google.com/?q=Mahavir+Skoda+Jubilee+Hills+Hyderabad",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Gurudev Škoda — Anna Nagar",
    brandSlug: "skoda",
    vehicleSlug: "skoda-slavia",
    dealerCode: "SK-CHE-10",
    outletType: OutletType.THREE_S_FACILITY,
    address: "100 Feet Road, Near Thirumangalam Flyover, Anna Nagar West",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600040",
    phone: "+91 98400 99887",
    email: "annanagar@gurudevskoda.com",
    rating: 4.5,
    reviewCount: 285,
    latitude: 13.0878,
    longitude: 77.1994,
    googleMapsUrl: "https://maps.google.com/?q=Gurudev+Skoda+Anna+Nagar+Chennai",
    operatingHours: "9:00 AM - 7:00 PM (Mon-Sun)",
  },

  // =========================================================================
  // 2. HYUNDAI INDIA DEALERS (Serving Hyundai Verna)
  // =========================================================================
  {
    name: "Koncept Hyundai — Okhla Industrial Area",
    brandSlug: "hyundai",
    vehicleSlug: "hyundai-verna",
    dealerCode: "HY-DEL-01",
    outletType: OutletType.THREE_S_FACILITY,
    address: "A-5, Okhla Industrial Area Phase 1, Main Road",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110020",
    phone: "+91 98110 55443",
    email: "sales.okhla@koncepthyundai.com",
    rating: 4.7,
    reviewCount: 560,
    latitude: 28.5355,
    longitude: 77.2798,
    googleMapsUrl: "https://maps.google.com/?q=Koncept+Hyundai+Okhla+Delhi",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Hans Hyundai — Moti Nagar",
    brandSlug: "hyundai",
    vehicleSlug: "hyundai-verna",
    dealerCode: "HY-DEL-02",
    outletType: OutletType.THREE_S_FACILITY,
    address: "69/1A, Najafgarh Road, Moti Nagar Crossing",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110015",
    phone: "+91 98112 33445",
    email: "enquiry@hanshyundai.com",
    rating: 4.6,
    reviewCount: 490,
    latitude: 28.6534,
    longitude: 77.1421,
    googleMapsUrl: "https://maps.google.com/?q=Hans+Hyundai+Moti+Nagar+Delhi",
    operatingHours: "9:00 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Deep Hyundai — Rohini",
    brandSlug: "hyundai",
    vehicleSlug: "hyundai-verna",
    dealerCode: "HY-DEL-03",
    outletType: OutletType.SHOWROOM,
    address: "Plot No. 1, Block C-9, Sector 7, Rohini",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110085",
    phone: "+91 98118 77665",
    email: "rohini@deephyundai.com",
    rating: 4.5,
    reviewCount: 310,
    latitude: 28.7061,
    longitude: 77.1192,
    googleMapsUrl: "https://maps.google.com/?q=Deep+Hyundai+Rohini+Delhi",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Himgiri Hyundai — Sector 14 Gurugram",
    brandSlug: "hyundai",
    vehicleSlug: "hyundai-verna",
    dealerCode: "HY-GGN-04",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Old Delhi-Gurgaon Road, Near Sector 14 Crossing",
    city: "Gurugram",
    state: "Haryana",
    pincode: "122001",
    phone: "+91 99103 44556",
    email: "sales.ggn@himgirihyundai.com",
    rating: 4.7,
    reviewCount: 430,
    latitude: 28.4732,
    longitude: 77.0428,
    googleMapsUrl: "https://maps.google.com/?q=Himgiri+Hyundai+Sector+14+Gurgaon",
    operatingHours: "9:00 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Modi Hyundai — Malad West",
    brandSlug: "hyundai",
    vehicleSlug: "hyundai-verna",
    dealerCode: "HY-MUM-05",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Evershine Mall, Link Road, Chincholi Bunder, Malad West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400064",
    phone: "+91 98200 44321",
    email: "malad@modihyundai.com",
    rating: 4.8,
    reviewCount: 620,
    latitude: 19.1822,
    longitude: 72.8344,
    googleMapsUrl: "https://maps.google.com/?q=Modi+Hyundai+Malad+West+Mumbai",
    operatingHours: "9:30 AM - 8:00 PM (Mon-Sun)",
  },
  {
    name: "Shreenath Hyundai — Chembur",
    brandSlug: "hyundai",
    vehicleSlug: "hyundai-verna",
    dealerCode: "HY-MUM-06",
    outletType: OutletType.SHOWROOM,
    address: "Sion-Trombay Road, Diamond Garden, Chembur",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400071",
    phone: "+91 98208 77665",
    email: "chembur@shreenathhyundai.com",
    rating: 4.6,
    reviewCount: 340,
    latitude: 19.0583,
    longitude: 72.9015,
    googleMapsUrl: "https://maps.google.com/?q=Shreenath+Hyundai+Chembur+Mumbai",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Trident Hyundai — Indiranagar",
    brandSlug: "hyundai",
    vehicleSlug: "hyundai-verna",
    dealerCode: "HY-BLR-07",
    outletType: OutletType.THREE_S_FACILITY,
    address: "No. 46, 100 Feet Road, HAL 2nd Stage, Indiranagar",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560038",
    phone: "+91 98451 22334",
    email: "sales.indiranagar@tridenthyundai.com",
    rating: 4.8,
    reviewCount: 710,
    latitude: 12.9716,
    longitude: 77.6412,
    googleMapsUrl: "https://maps.google.com/?q=Trident+Hyundai+Indiranagar+Bengaluru",
    operatingHours: "9:00 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Blue Hyundai — Koramangala",
    brandSlug: "hyundai",
    vehicleSlug: "hyundai-verna",
    dealerCode: "HY-BLR-08",
    outletType: OutletType.SHOWROOM,
    address: "80 Feet Road, 4th Block, Koramangala, Near Sony World Signal",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560034",
    phone: "+91 98458 44332",
    email: "koramangala@bluehyundai.in",
    rating: 4.6,
    reviewCount: 380,
    latitude: 12.9345,
    longitude: 77.6256,
    googleMapsUrl: "https://maps.google.com/?q=Blue+Hyundai+Koramangala+Bengaluru",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Kundandani Hyundai — Swargate",
    brandSlug: "hyundai",
    vehicleSlug: "hyundai-verna",
    dealerCode: "HY-PUN-09",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Shankarsheth Road, Swargate, Near Kumar Pacific Mall",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411037",
    phone: "+91 98225 11223",
    email: "sales@kundandanihyundai.com",
    rating: 4.7,
    reviewCount: 440,
    latitude: 18.5012,
    longitude: 73.8643,
    googleMapsUrl: "https://maps.google.com/?q=Kundandani+Hyundai+Swargate+Pune",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "KUN United Hyundai — Gachibowli",
    brandSlug: "hyundai",
    vehicleSlug: "hyundai-verna",
    dealerCode: "HY-HYD-10",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Old Mumbai Highway, Telecom Nagar, Gachibowli",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500032",
    phone: "+91 98495 66778",
    email: "gachibowli@kunhyundai.com",
    rating: 4.8,
    reviewCount: 520,
    latitude: 17.4401,
    longitude: 78.3489,
    googleMapsUrl: "https://maps.google.com/?q=KUN+Hyundai+Gachibowli+Hyderabad",
    operatingHours: "9:00 AM - 7:30 PM (Mon-Sun)",
  },

  // =========================================================================
  // 3. HONDA CARS INDIA DEALERS (Serving Honda City)
  // =========================================================================
  {
    name: "Courtesy Honda — Okhla Phase 1",
    brandSlug: "honda-cars",
    vehicleSlug: "honda-city",
    dealerCode: "HC-DEL-01",
    outletType: OutletType.THREE_S_FACILITY,
    address: "B-231, Okhla Industrial Area Phase I, Main Road",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110020",
    phone: "+91 98110 99881",
    email: "sales@courtesyhonda.com",
    rating: 4.7,
    reviewCount: 510,
    latitude: 28.5298,
    longitude: 77.2789,
    googleMapsUrl: "https://maps.google.com/?q=Courtesy+Honda+Okhla+Delhi",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Prime Honda — Patparganj",
    brandSlug: "honda-cars",
    vehicleSlug: "honda-city",
    dealerCode: "HC-DEL-02",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Plot No. 13, Patparganj Industrial Area, Near Anand Vihar",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110092",
    phone: "+91 98115 11223",
    email: "patparganj@primehonda.in",
    rating: 4.6,
    reviewCount: 420,
    latitude: 28.6312,
    longitude: 77.3087,
    googleMapsUrl: "https://maps.google.com/?q=Prime+Honda+Patparganj+Delhi",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Ring Road Honda — Peeragarhi",
    brandSlug: "honda-cars",
    vehicleSlug: "honda-city",
    dealerCode: "HC-DEL-03",
    outletType: OutletType.SHOWROOM,
    address: "Rohtak Road, Peeragarhi Crossing, West Delhi",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110087",
    phone: "+91 98118 44332",
    email: "peeragarhi@ringroadhonda.com",
    rating: 4.5,
    reviewCount: 360,
    latitude: 28.6791,
    longitude: 77.0945,
    googleMapsUrl: "https://maps.google.com/?q=Ring+Road+Honda+Peeragarhi+Delhi",
    operatingHours: "9:30 AM - 7:00 PM (Mon-Sun)",
  },
  {
    name: "Regent Honda — Thane West",
    brandSlug: "honda-cars",
    vehicleSlug: "honda-city",
    dealerCode: "HC-MUM-04",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Ghodbunder Road, Anand Nagar, Next to Hypercity Mall",
    city: "Thane",
    state: "Maharashtra",
    pincode: "400615",
    phone: "+91 98205 66778",
    email: "thane.sales@regenthonda.com",
    rating: 4.8,
    reviewCount: 590,
    latitude: 19.2612,
    longitude: 72.9734,
    googleMapsUrl: "https://maps.google.com/?q=Regent+Honda+Ghodbunder+Road+Thane",
    operatingHours: "9:00 AM - 8:00 PM (Mon-Sun)",
  },
  {
    name: "Arya Honda — Prabhadevi",
    brandSlug: "honda-cars",
    vehicleSlug: "honda-city",
    dealerCode: "HC-MUM-05",
    outletType: OutletType.SHOWROOM,
    address: "Appasaheb Marathe Marg, Prabhadevi, South Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400025",
    phone: "+91 98200 99881",
    email: "prabhadevi@aryahonda.com",
    rating: 4.7,
    reviewCount: 440,
    latitude: 19.0142,
    longitude: 72.8276,
    googleMapsUrl: "https://maps.google.com/?q=Arya+Honda+Prabhadevi+Mumbai",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Magnum Honda — Kanakapura Road",
    brandSlug: "honda-cars",
    vehicleSlug: "honda-city",
    dealerCode: "HC-BLR-06",
    outletType: OutletType.THREE_S_FACILITY,
    address: "No. 118, Kanakapura Main Road, Sarakki Industrial Area",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560078",
    phone: "+91 98450 44556",
    email: "sales@magnumhonda.com",
    rating: 4.7,
    reviewCount: 480,
    latitude: 12.9056,
    longitude: 77.5732,
    googleMapsUrl: "https://maps.google.com/?q=Magnum+Honda+Kanakapura+Road+Bengaluru",
    operatingHours: "9:00 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Dakshin Honda — Lavelle Road",
    brandSlug: "honda-cars",
    vehicleSlug: "honda-city",
    dealerCode: "HC-BLR-07",
    outletType: OutletType.SHOWROOM,
    address: "Lavelle Road, Near Richmond Circle, CBD",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560001",
    phone: "+91 98455 88990",
    email: "lavelle@dakshinhonda.com",
    rating: 4.8,
    reviewCount: 520,
    latitude: 12.9698,
    longitude: 77.5998,
    googleMapsUrl: "https://maps.google.com/?q=Dakshin+Honda+Lavelle+Road+Bengaluru",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Crystal Honda — Bavdhan",
    brandSlug: "honda-cars",
    vehicleSlug: "honda-city",
    dealerCode: "HC-PUN-08",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Mumbai-Bangalore Highway, Bavdhan BK, Near Chandani Chowk",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411021",
    phone: "+91 98228 33445",
    email: "sales.bavdhan@crystalhonda.com",
    rating: 4.6,
    reviewCount: 390,
    latitude: 18.5145,
    longitude: 73.7821,
    googleMapsUrl: "https://maps.google.com/?q=Crystal+Honda+Bavdhan+Pune",
    operatingHours: "9:30 AM - 7:30 PM (Mon-Sun)",
  },
  {
    name: "Pride Honda — Madhapur",
    brandSlug: "honda-cars",
    vehicleSlug: "honda-city",
    dealerCode: "HC-HYD-09",
    outletType: OutletType.THREE_S_FACILITY,
    address: "Hitech City Main Road, Cyber Towers Junction, Madhapur",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500081",
    phone: "+91 98492 11223",
    email: "madhapur@pridehonda.com",
    rating: 4.8,
    reviewCount: 650,
    latitude: 17.4485,
    longitude: 78.3789,
    googleMapsUrl: "https://maps.google.com/?q=Pride+Honda+Madhapur+Hyderabad",
    operatingHours: "9:00 AM - 8:00 PM (Mon-Sun)",
  },
  {
    name: "Sundaram Honda — Mount Road",
    brandSlug: "honda-cars",
    vehicleSlug: "honda-city",
    dealerCode: "HC-CHE-10",
    outletType: OutletType.THREE_S_FACILITY,
    address: "180, Anna Salai (Mount Road), Teynampet",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600006",
    phone: "+91 98405 44321",
    email: "mountroad@sundaramhonda.com",
    rating: 4.7,
    reviewCount: 470,
    latitude: 13.0425,
    longitude: 78.2498,
    googleMapsUrl: "https://maps.google.com/?q=Sundaram+Honda+Anna+Salai+Chennai",
    operatingHours: "9:00 AM - 7:00 PM (Mon-Sun)",
  },
];

async function main() {
  console.log("=== Seeding Multi-Brand Authorized Dealer Network ===");

  // Pre-fetch brands and vehicles
  const brands = await prisma.brand.findMany();
  const vehicles = await prisma.vehicle.findMany({
    select: { id: true, slug: true, brandId: true },
  });

  const brandMap = new Map<string, string>();
  for (const b of brands) {
    brandMap.set(b.slug, b.id);
  }

  const vehicleMap = new Map<string, string>();
  for (const v of vehicles) {
    vehicleMap.set(v.slug, v.id);
  }

  // Clear existing dealers for a clean re-sync
  await prisma.dealer.deleteMany();
  console.log("Cleared old dealer records.");

  let insertedCount = 0;

  for (const d of DEALERS_SEED) {
    const brandId = brandMap.get(d.brandSlug);
    if (!brandId) {
      console.warn(`Brand slug "${d.brandSlug}" not found in database. Skipping ${d.name}.`);
      continue;
    }

    const vehicleId = vehicleMap.get(d.vehicleSlug) || null;

    await prisma.dealer.create({
      data: {
        brandId,
        vehicleId,
        name: d.name,
        dealerCode: d.dealerCode,
        outletType: d.outletType,
        address: d.address,
        city: d.city,
        state: d.state,
        pincode: d.pincode,
        phone: d.phone,
        email: d.email,
        rating: d.rating,
        reviewCount: d.reviewCount,
        latitude: d.latitude,
        longitude: d.longitude,
        googleMapsUrl: d.googleMapsUrl,
        operatingHours: d.operatingHours,
        isVerified: true,
      },
    });

    insertedCount++;
  }

  console.log(`Successfully seeded ${insertedCount} authorized dealers across Škoda, Hyundai, and Honda.`);
  console.log("=== Dealer Network Seeding Complete! ===");
}

main()
  .catch((e) => {
    console.error("Error seeding dealers:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
