import * as XLSX from 'xlsx';
import * as path from 'path';
import * as fs from 'fs';

const targetDir = path.join(
  process.cwd(),
  'public',
  'vehicles',
  'cars',
  'hyundai',
  'hyundai-creta'
);

if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

const cretaPricingData = [
  // --- 1.5L MPi Petrol (Naturally Aspirated) ---
  {
    'Trim / Variant': 'Creta E',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 10.91,
    'Ex-Showroom Price (INR)': 1091000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta EX',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 12.07,
    'Ex-Showroom Price (INR)': 1207000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta EX (O)',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 13.14,
    'Ex-Showroom Price (INR)': 1314000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta EX (O) CVT',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Automatic (CVT / IVT)',
    'Ex-Showroom Price (Lakh)': 14.5,
    'Ex-Showroom Price (INR)': 1450000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta S (O)',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 14.21,
    'Ex-Showroom Price (INR)': 1421000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta S (O) Knight',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 14.39,
    'Ex-Showroom Price (INR)': 1439000,
    'Edition / Theme': 'Knight Edition',
  },
  {
    'Trim / Variant': 'Creta S (O) CVT',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Automatic (CVT / IVT)',
    'Ex-Showroom Price (Lakh)': 15.66,
    'Ex-Showroom Price (INR)': 1566000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta SX',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 15.04,
    'Ex-Showroom Price (INR)': 1504000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta SX Dual Tone',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 15.19,
    'Ex-Showroom Price (INR)': 1519000,
    'Edition / Theme': 'Dual Tone',
  },
  {
    'Trim / Variant': 'Creta SX Premium',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 16.34,
    'Ex-Showroom Price (INR)': 1634000,
    'Edition / Theme': 'Premium',
  },
  {
    'Trim / Variant': 'Creta SX Premium CVT',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Automatic (CVT / IVT)',
    'Ex-Showroom Price (Lakh)': 17.79,
    'Ex-Showroom Price (INR)': 1779000,
    'Edition / Theme': 'Premium',
  },
  {
    'Trim / Variant': 'Creta SX Premium CVT Dual Tone',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Automatic (CVT / IVT)',
    'Ex-Showroom Price (Lakh)': 17.94,
    'Ex-Showroom Price (INR)': 1794000,
    'Edition / Theme': 'Premium Dual Tone',
  },
  {
    'Trim / Variant': 'Creta King Edition Petrol MT',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 17.28,
    'Ex-Showroom Price (INR)': 1728000,
    'Edition / Theme': 'King Edition',
  },
  {
    'Trim / Variant': 'Creta King Edition Petrol CVT',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Automatic (CVT / IVT)',
    'Ex-Showroom Price (Lakh)': 18.69,
    'Ex-Showroom Price (INR)': 1869000,
    'Edition / Theme': 'King Edition',
  },
  {
    'Trim / Variant': 'Creta King Knight Edition Petrol CVT',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Automatic (CVT / IVT)',
    'Ex-Showroom Price (Lakh)': 18.83,
    'Ex-Showroom Price (INR)': 1883000,
    'Edition / Theme': 'King Knight Edition',
  },
  {
    'Trim / Variant': 'Creta King Knight Edition Petrol CVT DT',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Automatic (CVT / IVT)',
    'Ex-Showroom Price (Lakh)': 18.84,
    'Ex-Showroom Price (INR)': 1884000,
    'Edition / Theme': 'King Knight Dual Tone',
  },
  {
    'Trim / Variant': 'Creta King Lounge Edition Petrol CVT',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Automatic (CVT / IVT)',
    'Ex-Showroom Price (Lakh)': 19.22,
    'Ex-Showroom Price (INR)': 1922000,
    'Edition / Theme': 'King Lounge Edition',
  },
  {
    'Trim / Variant': 'Creta King Lounge Edition Petrol CVT DT',
    'Fuel Type': 'Petrol',
    'Engine Type': '1.5L MPi Petrol',
    'Displacement': '1497 cc',
    'Transmission': 'Automatic (CVT / IVT)',
    'Ex-Showroom Price (Lakh)': 19.37,
    'Ex-Showroom Price (INR)': 1937000,
    'Edition / Theme': 'King Lounge Dual Tone',
  },

  // --- 1.5L Turbo GDi Petrol ---
  {
    'Trim / Variant': 'Creta King Edition 1.5 Turbo DCT',
    'Fuel Type': 'Turbo Petrol',
    'Engine Type': '1.5L Turbo GDi Petrol',
    'Displacement': '1482 cc Turbo',
    'Transmission': 'Automatic (7-Speed DCT)',
    'Ex-Showroom Price (Lakh)': 19.91,
    'Ex-Showroom Price (INR)': 1991000,
    'Edition / Theme': 'King Edition',
  },
  {
    'Trim / Variant': 'Creta King Edition 1.5 Turbo DCT DT',
    'Fuel Type': 'Turbo Petrol',
    'Engine Type': '1.5L Turbo GDi Petrol',
    'Displacement': '1482 cc Turbo',
    'Transmission': 'Automatic (7-Speed DCT)',
    'Ex-Showroom Price (Lakh)': 20.06,
    'Ex-Showroom Price (INR)': 2006000,
    'Edition / Theme': 'King Edition Dual Tone',
  },

  // --- 1.5L U2 CRDi Diesel ---
  {
    'Trim / Variant': 'Creta E Diesel',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 12.53,
    'Ex-Showroom Price (INR)': 1253000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta EX Diesel',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 13.66,
    'Ex-Showroom Price (INR)': 1366000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta EX (O) Diesel',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 14.73,
    'Ex-Showroom Price (INR)': 1473000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta EX (O) Diesel AT',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Automatic (6-Speed TC)',
    'Ex-Showroom Price (Lakh)': 16.08,
    'Ex-Showroom Price (INR)': 1608000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta S (O) Diesel',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 15.85,
    'Ex-Showroom Price (INR)': 1585000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta S (O) Knight Diesel',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 16.03,
    'Ex-Showroom Price (INR)': 1603000,
    'Edition / Theme': 'Knight Edition',
  },
  {
    'Trim / Variant': 'Creta S (O) Diesel AT',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Automatic (6-Speed TC)',
    'Ex-Showroom Price (Lakh)': 17.3,
    'Ex-Showroom Price (INR)': 1730000,
    'Edition / Theme': 'Standard',
  },
  {
    'Trim / Variant': 'Creta SX Premium Diesel',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 17.93,
    'Ex-Showroom Price (INR)': 1793000,
    'Edition / Theme': 'Premium',
  },
  {
    'Trim / Variant': 'Creta SX Premium Diesel DT',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 18.08,
    'Ex-Showroom Price (INR)': 1808000,
    'Edition / Theme': 'Premium Dual Tone',
  },
  {
    'Trim / Variant': 'Creta King Edition Diesel MT',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 18.86,
    'Ex-Showroom Price (INR)': 1886000,
    'Edition / Theme': 'King Edition',
  },
  {
    'Trim / Variant': 'Creta King Edition Diesel MT DT',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Manual (6-Speed MT)',
    'Ex-Showroom Price (Lakh)': 19.01,
    'Ex-Showroom Price (INR)': 1901000,
    'Edition / Theme': 'King Edition Dual Tone',
  },
  {
    'Trim / Variant': 'Creta King Edition Diesel AT',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Automatic (6-Speed TC)',
    'Ex-Showroom Price (Lakh)': 19.78,
    'Ex-Showroom Price (INR)': 1978000,
    'Edition / Theme': 'King Edition',
  },
  {
    'Trim / Variant': 'Creta King Edition Diesel AT DT',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Automatic (6-Speed TC)',
    'Ex-Showroom Price (Lakh)': 19.93,
    'Ex-Showroom Price (INR)': 1993000,
    'Edition / Theme': 'King Edition Dual Tone',
  },
  {
    'Trim / Variant': 'Creta King Knight Edition Diesel AT',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Automatic (6-Speed TC)',
    'Ex-Showroom Price (Lakh)': 20.11,
    'Ex-Showroom Price (INR)': 2011000,
    'Edition / Theme': 'King Knight Edition',
  },
  {
    'Trim / Variant': 'Creta King Lounge Edition Diesel AT',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Automatic (6-Speed TC)',
    'Ex-Showroom Price (Lakh)': 20.31,
    'Ex-Showroom Price (INR)': 2031000,
    'Edition / Theme': 'King Lounge Edition',
  },
  {
    'Trim / Variant': 'Creta King Lounge Edition Diesel AT DT',
    'Fuel Type': 'Diesel',
    'Engine Type': '1.5L U2 CRDi Diesel',
    'Displacement': '1493 cc Turbo',
    'Transmission': 'Automatic (6-Speed TC)',
    'Ex-Showroom Price (Lakh)': 20.46,
    'Ex-Showroom Price (INR)': 2046000,
    'Edition / Theme': 'King Lounge Dual Tone',
  },
];

const wb = XLSX.utils.book_new();

const wsAll = XLSX.utils.json_to_sheet(cretaPricingData);
XLSX.utils.book_append_sheet(wb, wsAll, 'All Variants');

const wsPetrol = XLSX.utils.json_to_sheet(
  cretaPricingData.filter((v) => v['Fuel Type'].includes('Petrol'))
);
XLSX.utils.book_append_sheet(wb, wsPetrol, 'Petrol Variants');

const wsDiesel = XLSX.utils.json_to_sheet(
  cretaPricingData.filter((v) => v['Fuel Type'] === 'Diesel')
);
XLSX.utils.book_append_sheet(wb, wsDiesel, 'Diesel Variants');

const outPath = path.join(targetDir, 'Price-Ex-ShowRoom.xlsx');
XLSX.writeFile(wb, outPath);

console.log('Successfully created Hyundai Creta price spreadsheet:');
console.log(outPath);